
#These options affect only the client that loads the mod.
[clientOnly]
	#Enabled tools, by their resource name. Eg: minecraft:diamond_hoe.
	enabledToolsID = []
	#Enabled tools, by their Class name. Eg: net.minecraft.item.TieredItem.
	enabledToolsClass = ["net.minecraft.item.TieredItem", "net.minecraft.item.ShootableItem", "net.minecraft.item.ShearsItem", "net.minecraft.item.FishingRodItem", "net.minecraft.item.TridentItem"]
	#Disabled tools, by their resource name. Eg: minecraft:diamond_hoe
	disabledToolsID = ["minecraft:shield"]
	#Disabled tools, by their Class name. Eg: net.minecraft.item.TieredItem
	disabledToolsClass = []
	#Tool orientation, by class file and degrees. Separate with ":" . See defaults for examples.
	toolOrientation = ["net.minecraft.item.ToolItem:180", "net.minecraft.item.HoeItem:180", "net.minecraft.item.FishingRodItem:180", "net.minecraft.item.TridentItem:180", "net.minecraft.item.ShootableItem:90"]
	#Some nbt tags will cause back tools to appear improperly. Use this setting to cleanse the item tags.
	nbtCleaner = ["Damage", "Charged", "ChargedProjectiles"]

